### ISSUE TITLE
Memory access fault by GPU node-1 RX 480 -  Ubuntu 18.x

### ISSUE THREAD

**Issue by gateway** [RadeonOpenCompute/ROCR-Runtime#50]
Hi, I'm testing our various already made software packages for Neural Style Transfers systems that use Tensor Flow.  I'm trying to get this one up and running on my AMD RX 480 https://github.com/cysmith/neural-style-tf

However I keep running into this error. 

`Memory access fault by GPU node-1 (Agent handle: 0x559d51a74e00) on address 0x5e2206000. Reason: Page not present or supervisor privilege.`

My system is pretty basic:

Ubuntu 18.x Desktop
ROCm 1.9.2

Here is a dump output from running the script to transfer a demo style to an image.

`bash stylize_image.sh ./image_input/lion.jpg ./styles/kandinsky.jpg`

```
Rendering stylized image. This may take a while...
2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0]
WARNING:tensorflow:From /home/gateway/.local/lib/python2.7/site-packages/tensorflow/python/ops/distributions/distribution.py:265: __init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
WARNING:tensorflow:From /home/gateway/.local/lib/python2.7/site-packages/tensorflow/python/ops/distributions/bernoulli.py:169: __init__ (from tensorflow.python.ops.distributions.kullback_leibler) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.

---- RENDERING SINGLE IMAGE ----

2018-12-22 10:39:13.204832: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
2018-12-22 10:39:13.205173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1530] Found device 0 with properties: 
name: Ellesmere [Radeon RX 470/480]
AMDGPU ISA: gfx803
memoryClockRate (GHz) 1.29
pciBusID 0000:01:00.0
Total memory: 4.00GiB
Free memory: 3.75GiB
2018-12-22 10:39:13.205189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Adding visible gpu devices: 0
2018-12-22 10:39:13.205206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1051] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-22 10:39:13.205212: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1057]      0 
2018-12-22 10:39:13.205217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1070] 0:   N 
2018-12-22 10:39:13.205249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1189] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3540 MB memory) -> physical GPU (device: 0, name: Ellesmere [Radeon RX 470/480], pci bus id: 0000:01:00.0)

BUILDING VGG-19 NETWORK
loading model weights...
constructing layers...
LAYER GROUP 1
--conv1_1 | shape=(1, 512, 512, 64) | weights_shape=(3, 3, 3, 64)
--relu1_1 | shape=(1, 512, 512, 64) | bias_shape=(64,)
--conv1_2 | shape=(1, 512, 512, 64) | weights_shape=(3, 3, 64, 64)
--relu1_2 | shape=(1, 512, 512, 64) | bias_shape=(64,)
--pool1   | shape=(1, 256, 256, 64)
LAYER GROUP 2
--conv2_1 | shape=(1, 256, 256, 128) | weights_shape=(3, 3, 64, 128)
--relu2_1 | shape=(1, 256, 256, 128) | bias_shape=(128,)
--conv2_2 | shape=(1, 256, 256, 128) | weights_shape=(3, 3, 128, 128)
--relu2_2 | shape=(1, 256, 256, 128) | bias_shape=(128,)
--pool2   | shape=(1, 128, 128, 128)
LAYER GROUP 3
--conv3_1 | shape=(1, 128, 128, 256) | weights_shape=(3, 3, 128, 256)
--relu3_1 | shape=(1, 128, 128, 256) | bias_shape=(256,)
--conv3_2 | shape=(1, 128, 128, 256) | weights_shape=(3, 3, 256, 256)
--relu3_2 | shape=(1, 128, 128, 256) | bias_shape=(256,)
--conv3_3 | shape=(1, 128, 128, 256) | weights_shape=(3, 3, 256, 256)
--relu3_3 | shape=(1, 128, 128, 256) | bias_shape=(256,)
--conv3_4 | shape=(1, 128, 128, 256) | weights_shape=(3, 3, 256, 256)
--relu3_4 | shape=(1, 128, 128, 256) | bias_shape=(256,)
--pool3   | shape=(1, 64, 64, 256)
LAYER GROUP 4
--conv4_1 | shape=(1, 64, 64, 512) | weights_shape=(3, 3, 256, 512)
--relu4_1 | shape=(1, 64, 64, 512) | bias_shape=(512,)
--conv4_2 | shape=(1, 64, 64, 512) | weights_shape=(3, 3, 512, 512)
--relu4_2 | shape=(1, 64, 64, 512) | bias_shape=(512,)
--conv4_3 | shape=(1, 64, 64, 512) | weights_shape=(3, 3, 512, 512)
--relu4_3 | shape=(1, 64, 64, 512) | bias_shape=(512,)
--conv4_4 | shape=(1, 64, 64, 512) | weights_shape=(3, 3, 512, 512)
--relu4_4 | shape=(1, 64, 64, 512) | bias_shape=(512,)
--pool4   | shape=(1, 32, 32, 512)
LAYER GROUP 5
--conv5_1 | shape=(1, 32, 32, 512) | weights_shape=(3, 3, 512, 512)
--relu5_1 | shape=(1, 32, 32, 512) | bias_shape=(512,)
--conv5_2 | shape=(1, 32, 32, 512) | weights_shape=(3, 3, 512, 512)
--relu5_2 | shape=(1, 32, 32, 512) | bias_shape=(512,)
--conv5_3 | shape=(1, 32, 32, 512) | weights_shape=(3, 3, 512, 512)
--relu5_3 | shape=(1, 32, 32, 512) | bias_shape=(512,)
--conv5_4 | shape=(1, 32, 32, 512) | weights_shape=(3, 3, 512, 512)
--relu5_4 | shape=(1, 32, 32, 512) | bias_shape=(512,)
--pool5   | shape=(1, 16, 16, 512)
Memory access fault by GPU node-1 (Agent handle: 0x559701510fa0) on address 0x5e2203000. Reason: Page not present or supervisor privilege.
stylize_image.sh: line 44: 19003 Aborted                 (core dumped) python neural_style.py --content_img "${content_filename}" --content_img_dir "${content_dir}" --style_imgs "${style_filename}" --style_imgs_dir "${style_dir}" --device "${device}" --verbose
```

Please take note I'm just getting into programming/testing with neural styles and had a bunch of RX 480 cards laying around to test with.

Any suggestions?

**Comment by jlgreathouse** [comment]
This usually indicates that one of your GPU kernels has a buffer overflow in it. Are you using AMD's tensorflow implementation for your tests? If so, you should likely try asking in [their issue tracker](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream).

**Comment by skeelyamd** [comment]
Compiler issue has been fixed.
